### ISSUE TITLE
ValueError: No data found.

### ISSUE THREAD

**Issue by anawas** [i4Ds/radiospectra#19]
Sometimes a get the following combined exception. The main reason is on the last line. There was no data loaded from fits:
```python
Traceback (most recent call last):
  File "/Users/andreas/miniforge3/envs/ecallisto/lib/python3.9/site-packages/radiospectra/sources/callisto.py", line 530, in from_range
    spec = cls.combine_frequencies(
  File "/Users/andreas/miniforge3/envs/ecallisto/lib/python3.9/site-packages/radiospectra/spectrogram.py", line 1727, in combine_frequencies
    raise ValueError("Need at least one spectrogram.")
ValueError: Need at least one spectrogram.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/VMs/astrophysics/raumschiff/burstextractor/burstlist.py", line 97, in extract_burst
    s = CallistoSpectrogram.from_range(
  File "/Users/andreas/miniforge3/envs/ecallisto/lib/python3.9/site-packages/radiospectra/sources/callisto.py", line 595, in from_range
    raise ValueError("No data found.")
ValueError: No data found.
```

## How to reproduce
```python
start = datetime.datetime(2022, 8, 4, 3, 14)
end = datetime.datetime(2022, 8, 4, 3, 26)
spec = CallistoSpectrogram.from_range("Malaysia_Banting", start, end)
```

**Comment by anawas** [comment]
Closed because it is not a code issue. There is a typo in the instrument's name in the burst list. Should be Malaysia-Banting instead of Malaysia_Banting.
